#!/bin/sh

LABEL="\uf1d1"
FAN="fan2"
SPEED=`sensors | grep $FAN | cut -c16-19`
SPEED="${SPEED:-1}"

if [ "$SPEED" -lt 500 ]; then
    printf "\n"
    printf "\n"
    exit 0
fi
printf "<span color=\"#9e8f07\">$LABEL $SPEED</span>\n"
printf "<span color=\"#9e8f07\">$LABEL $SPEED</span>\n"
