#!/bin/bash

if [[ -z "$INTERFACE" ]] ; then
    INTERFACE="${BLOCK_INSTANCE:-wlan0}"
fi

if [[ ! -d /sys/class/net/${INTERFACE}/wireless ]]; then
    echo ""
    exit
fi

if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
    echo "down"
    echo "down"
    echo "#FF0000"
    exit
fi

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

# color
if [[ $QUALITY -ge 80 ]]; then
    echo "📶 <span color='#719e07'>$QUALITY%</span>" # full text
    echo "📶 <span color='#719e07'>$QUALITY%</span>" # short text
elif [[ $QUALITY -ge 60 ]]; then
    echo "📶 <span color='#2aa198'>$QUALITY%</span>" # full text
    echo "📶 <span color='#2aa198'>$QUALITY%</span>" # short text
elif [[ $QUALITY -ge 40 ]]; then
    echo "📶 <span color='#b58900'>$QUALITY%</span>" # full text
    echo "📶 <span color='#b58900'>$QUALITY%</span>" # short text
else
    echo "📶 <span color='#cb4b16'>$QUALITY%</span>" # full text
    echo "📶 <span color='#cb4b16'>$QUALITY%</span>" # short text
fi
