#!/usr/bin/env python
import sys, os, subprocess, time, re

def get_active_window_title():
    root = subprocess.Popen(['xprop', '-root', '_NET_ACTIVE_WINDOW'], stdout=subprocess.PIPE)
    stdout, stderr = root.communicate()

    m = re.search(b'^_NET_ACTIVE_WINDOW.* ([\w]+)$', stdout)
    if m != None:
        window_id = m.group(1)
        if window_id != b"0x0":
            window = subprocess.Popen(['xprop', '-id', window_id, 'WM_NAME'], stdout=subprocess.PIPE)
            stdout, stderr = window.communicate()
    else:
        return None

    match = re.match(b"WM_NAME\(\w+\) = (?P<name>.+)$", stdout)
    if match != None:
        return match.group("name").strip(b'"')

    return None

if __name__ == "__main__":
    prevtitle = ''
    while True:
        time.sleep(0.25)
        title = get_active_window_title()
        if title != prevtitle:
            try:
                decoded = title.decode("utf-8")
            except:
                decoded = ""
            print("<span>🔮 " + decoded + "</span>")
            prevtitle = title
            sys.stdout.flush()
        time.sleep(0.25)
