#!/bin/sh

# Folder where this repository is
DIR=~/.dotfiles

installfile () {
    SOURCE=$1
    TARGET=$2

    if [ -e $TARGET ]; then
        echo -e " * \e[31mDelete\e[39m: $TARGET"
        rm -f $TARGET || true
    fi

    echo -e " * \e[33mLinking\e[39m: $SOURCE \t->\t $TARGET"
    ln -s $SOURCE $TARGET
}

for ENTRY in "$DIR/home"/*; do
    echo -e "[\e[32mhome\e[39m] installing $ENTRY"
    installfile $ENTRY ~/.${ENTRY##*/}
done

mkdir -p ~/.config

for ENTRY in "$DIR/config"/*; do
    echo -e "[\e[32m.config\e[39m] installing $ENTRY"
    installfile $ENTRY ~/.config/${ENTRY##*/}
done

