#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

if [[ -z "$EDITOR" ]]; then
  export EDITOR='nano'
fi
if [[ -z "$VISUAL" ]]; then
  export VISUAL='nano'
fi
if [[ -z "$PAGER" ]]; then
  export PAGER='less'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Variables
#

# Check if ~/Projektek/Webandmore/Internal exists
export WAM_SHARED="$HOME/Projektek/Webandmore/Internal"
export MOZ_ENABLE_WAYLAND=1 
export GTK_THEME=Adwaita:dark
export WLR_DRM_DEVICES=/dev/dri/card1
export GSK_RENDERER=ngl
export ELECTRON_OZONE_PLATFORM_HINT=wayland
export NVM_DIR="$HOME/.nvm"

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
# @TODO: Fix zshenv to load this
path=(
  $HOME/.{,s}bin(N)
  $HOME/.local/{,s}bin
  $HOME/.yarn/bin
  $HOME/.config/composer/vendor/bin
  $WAM_SHARED/bin
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/{,s}bin(N)
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
if [[ -z "$LESS" ]]; then
  export LESS='-g -i -M -R -S -w -X -z-4'
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Start Hyperland if it is installed and we are on tty1.
if [[ $(tty) == /dev/tty1 ]]; then
  if command -v hyprctl >/dev/null && command -v uwsm >/dev/null; then
      echo -e " * Starting Hyprland..."
      if uwsm check may-start; then
          exec uwsm start hyprland.desktop
      fi
  fi
fi
