ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"
DISABLE_UPDATE_PROMPT=true
DISABLE_AUTO_UPDATE=true
DISABLE_UNTRACKED_FILES_DIRTY=true
DEFAULT_USER="bayi"

#neofetch --kitty ~/.dotfiles/arch.svg --size 10%

# Compinit csak egyszer naponta
autoload -Uz compinit
setopt EXTENDEDGLOB
for dump in $ZSH_COMPDUMP(#qN.m1); do
  compinit
  if [[ -s "$dump" && (! -s "$dump.zwc" || "$dump" -nt "$dump.zwc") ]]; then
    zcompile "$dump"
  fi
  echo "Initializing Completions..."
done
unsetopt EXTENDEDGLOB
compinit -C

plugins=(git adb archlinux common-aliases cp catimg laravel symfony2)

source $ZSH/oh-my-zsh.sh

typeset -U path
path=(~/.Bin ~/.composer/vendor/bin ~/.yarn/bin $path)

bindkey -e
bindkey "^[OA" up-line-or-beginning-search
bindkey "^[OB" down-line-or-beginning-search

# Suffix aliases
alias -s html=chromium
alias -s php=vim
alias -s jpg=eog
alias -s jpeg=eog
alias -s png=eog
alias -s bmp=eog
alias -s gif=eog
alias -s avi=mpv
alias -s mp4=mpv
alias -s 3gp=mpv
alias -s wmv=mpv
alias -s zip=file-roller
alias -s pdf=chromium
alias -s txt=vim
alias -s c=vim
alias -s cpp=vim
alias -s h=vim
alias -s js=vim
alias -s json=vim

bindkey "^[[H" beginning-of-line
bindkey "^[[2~" overwrite-mode
bindkey "^[[3~" delete-char
bindkey "^[[F" end-of-line
bindkey "^[[5~" history-beginning-search-backward
bindkey "^[[6~" history-beginning-search-forward

function gitdiff() {
    git diff --no-ext-diff -w "$@" | vim -R -
}

alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"

function kepmegosztas() {
    x11vnc -viewonly -display :0 -noxwarppointer -forever -loop -shared -clip 1920x1080+1920+0 -cursor most -nopw -ncache 10 -ncache_cr -nobell -noxdamage -noxfixes -noxrecord -scale $@ -noncache -xrandr -noclipboard -norc
}
function kepmegosztasjo() {
    x11vnc -display :0 -noxwarppointer -multiptr -forever -loop -shared -clip 1920x1080+1920+0 -nopw -ncache 10 -ncache_cr -nobell -noxdamage -noxfixes -noxrecord -scale 1776x1000 -noncache -xrandr -noclipboard -norc -scale_cursor 1 -nolookup -nossl -input M,M
}
function gitall() {
    git add .
    if [ "$1" != "" ]
    then
        git commit -m "$1"
    else
        git commit -m update # default commit message is `update`
    fi
    git push origin HEAD
}
alias kepmegosztashd="kepmegosztas 1776x1000"
alias kepmegosztasld="kepmegosztas 1280x720"
#alias mondd='espeak -vhu+f2'
alias mondd='espeak -vhu'
alias midi='fluidsynth -a alsa -i /usr/share/soundfonts/FluidR3_GM2-2.sf2'
alias artisan="php artisan"
alias gg="git pull && git push"
alias kiafasztamad="sudo netstat -ntu | awk '{print $5}' | grep -iv \"[address|server]\" | grep -v ::1 | grep -v 127.0.0.1 | grep -v 10.0. | cut -d: -f1 | sort | uniq -c | sort -n"
alias muzsika="curl -sLN http://ai-radio.org/320.opus | opusdec - - | aplay -qfdat"
alias gitupdate='(for l in `find . -name .git | xargs -i dirname {}` ; do cd $l; pwd; git pull; cd -; done)'
alias pp='ps uxaf | most'
alias ffs='sudo `fc -n -l -1`'
alias randomscreen='hexdump -C < /dev/urandom | grep "ca fe"'
alias pd='popd'
alias gitkurvanagyfileok="git rev-list --objects --all | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' | awk '/^blob/ {print substr($0,6)}' | sort --numeric-sort --key=2 | cut --complement --characters=13-40 | numfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest"
alias helyfoglalas='du -cha --max-depth=1 / | grep -E "M|G"'
alias icat='kitty +kitten icat'
alias valtozottfileok='git diff --name-only --relative'
alias openports='sudo netstat -lnpt'

#Magyar bill wayland alatt
export XKB_DEFAULT_LAYOUT=hu
#Sötét GTK téma
#export GTK_THEME=Adwaita:dark

export ANDROID_HOME=/home/bayi/Work/_Android_/Sdk
export XDG_CURRENT_DESKTOP=GNOME

export EDITOR=vim
export PAGER=most
export TERMINAL=kitty

# Ctrl+S -re ne csinaljon semmit a terminal
stty -ixon

# Oh my zsh betöltése
source ~/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
#source /usr/share/nvm/init-nvm.sh

# Calculator
function =
{
    set -o localoptions -o noglob
    qalc -c \'"$@"\'
}
alias '?'='noglob ='
