#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Disable CTRL+S in terminals
stty -ixon

# Suffix aliases
alias -s html=chromium
alias -s php=vim
alias -s jpg=eog
alias -s jpeg=eog
alias -s png=eog
alias -s bmp=eog
alias -s gif=eog
alias -s avi=mpv
alias -s mp4=mpv
alias -s 3gp=mpv
alias -s wmv=mpv
alias -s zip=file-roller
alias -s pdf=chromium
alias -s txt=vim
alias -s c=vim
alias -s cpp=vim
alias -s h=vim
alias -s js=vim
alias -s json=vim

# Custom functions / aliases

if type "exa" > /dev/null; then
    alias ls="exa"
    alias ll="exa -alh"
    alias tree="exa --tree"
fi


if type "rg" > /dev/null; then
    alias rgrep="rg"
fi

if type "zoxide" > /dev/null; then
    eval "$(zoxide init zsh)"
    alias cd="z"
    alias cdb="z -"
fi

if type "entr" > /dev/null; then
    alias watch-c='find . -type f -regex ".*[ch]$" | entr make'
fi

if type "btm" > /dev/null; then
    alias top='btm --color nord'
fi

# Calculator
if type "qalc" > /dev/null; then
    function =
    {
        set -o localoptions -o noglob
        qalc -c \'"$@"\'
    }
    alias '?'='noglob ='
fi

function screen-share() {
    x11vnc -display :0 -noxwarppointer -multiptr -forever -loop -shared -clip 1920x1080+1920+0 -nopw -ncache 10 -ncache_cr -nobell -noxdamage -noxfixes -noxrecord -scale $@ -noncache -xrandr -noclipboard -norc -scale_cursor 1 -nolookup -nossl -input M,M
}

alias screen-share-hd="screen-share 1776x1000"
alias screen-share-ld="screen-share 1280x720"
alias say='espeak -vhu'
alias midi='fluidsynth -a alsa -i /usr/share/soundfonts/FluidR3_GM2-2.sf2'
alias artisan="php artisan"
alias tinker="php artisan tinker"
alias sf="php bin/console"
alias pp='ps uxaf'
alias ffs='sudo `fc -n -l -1`'
alias cpd='popd'
alias large-files='sudo du -cha --max-depth=1 | grep --color=always -E "[0-9]+(M|G)"'

## Random helpers
alias random-screen='hexdump -e "64/1 \"%02x \" \"\n\"" < /dev/urandom'
alias random-pw='cat /dev/urandom | tr -dc A-Za-z0-9@_-_ | head -c 16; echo " "'

## Git helpers
function git-diff-view() {
    git diff --no-ext-diff -w "$@" | vim -R -
}
alias gg="git pull && git push"
alias git-log="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias git-tree="git log --all --decorate --oneline --graph --date=relative --abbrev-commit"
alias git-tree-long="git log --graph --abbrev-commit --decorate --date=relative --all"
alias git-graph="git graphviz --first-parent master  | xdot -"
alias git-update='(for l in `find . -name .git | xargs -i dirname {}` ; do cd $l; pwd; git pull; cd -; done)'
alias git-changed-files='git diff --name-only --relative'
alias git-large-files="git rev-list --objects --all | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' | awk '/^blob/ {print substr($0,6)}' | sort --numeric-sort --key=2 | cut --complement --characters=13-40 | numfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest"

## Net helpers
alias net-open-ports='sudo netstat -lnpt | grep --color=never -E "(tcp|udp)"'
alias net-open-connections="sudo netstat -ntu"
alias net-ddos-check="sudo netstat -ntu | awk '{print $5}' | grep -iv \"[address|server]\" | grep -v ::1 | grep -v 127.0.0.1 | grep -v 10.0. | cut -d: -f1 | sort | uniq -c | sort -n"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/usr/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/usr/etc/profile.d/conda.sh" ]; then
        . "/usr/etc/profile.d/conda.sh"
    else
        export PATH="/usr/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

