#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# X Resources

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# X modmap

[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap

# Szerkeszto

export EDITOR="vim"
export PAGER="most"

exec i3
# exec gnome-session
