#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# X Resources

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# X modmap

[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap

# Szerkeszto

export EDITOR="vim"
export PAGER="most"

# Monitorok

# Gép
xrandr --output HDMI-2 --primary --output VGA-1 --left-of HDMI-2 --output HDMI-1 --right-of HDMI-2

# Színek
xrandr --output HDMI-1 --set "Broadcast RGB" "Full"
xrandr --output HDMI-2 --set "Broadcast RGB" "Full"

# Lapotop
# xrandr --output LVDS1 --primary

# i3

setxkbmap hu
xset -dpms
xset s off

exec i3
# exec gnome-session
