#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# X Resources

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# Szerkeszto

export EDITOR="vim"
export PAGER=$EDITOR

# Monitorok

# Gép
xrandr --output HDMI-2 --primary --output VGA-1 --left-of HDMI-2 --output HDMI-1 --right-of HDMI-2

# Lapotop
# xrandr --output LVDS1 --primary

# i3

exec i3

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice
